- name: Setup My Ubuntu Machine
  hosts: localhost
  become: true
  roles:
    - common
    - vscode
    - zsh

  vars:
    username: nik

    apt_packages:
    - git
    - jq
    - python3
    - python3-pip
    - mc
    - curl
    - tilix
    - htop
    - tldr
    - caffeine