---

- name: set gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: add vs code repository
  template:
      src: vscode.list.j2
      dest: /etc/apt/sources.list.d/vscode.list
      group: root
      owner: root
      mode: '0644'


- name: install vscode
  apt:
    name: code
    update_cache: true
  when:
    - vscode_install

- name: install vscode insiders
  apt:
    name: code-insiders
    update_cache: true
  when:
    - vscode_insiders_install
